export type Color='red'|'blue'|'green'|'yellow'|'wild';
export type Value='0'|'1'|'2'|'3'|'4'|'5'|'6'|'7'|'8'|'9'|'skip'|'reverse'|'draw2'|'wild'|'wild4';
export type Card={id:string;color:Color;value:Value};
export type Player={id:string;name:string;hand:Card[];isBot:boolean;calledLastCard:boolean;score:number};
export type Settings={mode:'bot'|'hotseat';playerCount:number;relaxedWild4:boolean};
export type GameState={players:Player[];drawPile:Card[];discardPile:Card[];activeColor:Color;currentPlayerIndex:number;direction:1|-1;status:'playing'|'finished';settings:Settings;winner:Player|null;drawnThisTurn:boolean;lastDrawnCard:Card|null;turnCount:number};
const colors:Color[]=['red','blue','green','yellow'];
const values:Value[]=['1','2','3','4','5','6','7','8','9','skip','reverse','draw2'];
export function createDeck():Card[]{const d:Card[]=[];for(const color of colors){d.push({id:`${color}-0-0`,color,value:'0'});for(const value of values){d.push({id:`${color}-${value}-0`,color,value});d.push({id:`${color}-${value}-1`,color,value});}}for(let i=0;i<4;i++){d.push({id:`wild-wild-${i}`,color:'wild',value:'wild'});d.push({id:`wild-wild4-${i}`,color:'wild',value:'wild4'});}return d}
export function shuffleDeck<T>(deck:T[]):T[]{const t=[...deck];for(let i=t.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[t[i],t[j]]=[t[j],t[i]]}return t}
const current=(s:GameState)=>s.players[s.currentPlayerIndex];
function nextIndex(s:GameState,steps=1){const n=s.players.length;return ((s.currentPlayerIndex+s.direction*steps)%n+n)%n}
export function isCardPlayable(card:Card,s:GameState){if(card.value==='wild')return true;if(card.value==='wild4'){if(s.settings.relaxedWild4)return true;return !current(s).hand.some(c=>c.color===s.activeColor)}const top=s.discardPile.at(-1);return card.color===s.activeColor||!!top&&card.value===top.value}
function reshuffle(s:GameState):GameState{if(s.discardPile.length<=1)return s;const top=s.discardPile.at(-1)!;return {...s,drawPile:shuffleDeck(s.discardPile.slice(0,-1)),discardPile:[top]}}
function drawTo(s:GameState,playerIndex:number,count:number){let state=s;for(let i=0;i<count;i++){if(state.drawPile.length===0)state=reshuffle(state);if(!state.drawPile.length)break;const [card,...rest]=state.drawPile;state={...state,drawPile:rest,players:state.players.map((p,i)=>i===playerIndex?{...p,hand:[...p.hand,card]}:p)}}return state}
function advance(s:GameState,steps=1):GameState{return {...s,currentPlayerIndex:nextIndex(s,steps),drawnThisTurn:false,lastDrawnCard:null}}
export function createNewGame(settings:Settings,names:string[]):GameState{const deck=shuffleDeck(createDeck());let pos=0;const players=names.map((name,i)=>({id:`player-${i}`,name,hand:deck.slice(pos,pos+=7),isBot:settings.mode==='bot'&&i>0,calledLastCard:false,score:0}));let drawPile=deck.slice(pos);let first=drawPile.shift()!;let guard=drawPile.length;while(!/^[0-9]$/.test(first.value)&&guard-->0){drawPile.push(first);first=drawPile.shift()!}return {players,drawPile,discardPile:[first],activeColor:first.color,currentPlayerIndex:0,direction:1,status:'playing',settings,winner:null,drawnThisTurn:false,lastDrawnCard:null,turnCount:0}}
export function getPlayableCards(s:GameState){return current(s).hand.filter(c=>isCardPlayable(c,s))}
export function drawCard(s:GameState){if(s.drawnThisTurn)return s;const i=s.currentPlayerIndex;const state=drawTo(s,i,1);const card=state.players[i].hand.at(-1)??null;return {...state,drawnThisTurn:true,lastDrawnCard:card&&isCardPlayable(card,state)?card:null}}
export function passTurn(s:GameState){return s.drawnThisTurn?{...advance(s),turnCount:s.turnCount+1}:s}
export function callLastCard(s:GameState,id:string){return {...s,players:s.players.map(p=>p.id===id&&p.hand.length===1?{...p,calledLastCard:true}:p)}}
export function penalizePlayer(s:GameState,id:string){const i=s.players.findIndex(p=>p.id===id);if(i<0)return s;const p=s.players[i];return p.hand.length===1&&!p.calledLastCard?drawTo(s,i,2):s}
export function playCard(s:GameState,id:string,chosenColor?:Exclude<Color,'wild'>):GameState{const p=current(s),card=p.hand.find(c=>c.id===id);if(!card)throw Error(`Card "${id}" not in current player's hand`);if(!isCardPlayable(card,s))throw Error(`Card "${id}" is not playable right now`);if((card.value==='wild'||card.value==='wild4')&&!chosenColor)throw Error('A colour must be chosen when playing a wild card');let state:GameState={...s,players:s.players.map((x,i)=>i===s.currentPlayerIndex?{...x,hand:x.hand.filter(c=>c.id!==id),calledLastCard:false}:x),discardPile:[...s.discardPile,card],activeColor:card.value==='wild'||card.value==='wild4'?chosenColor!:card.color};const hand=state.players[s.currentPlayerIndex].hand;if(hand.length===0)return {...state,status:'finished',winner:state.players[s.currentPlayerIndex]};let steps=1;if(card.value==='skip')steps=2;if(card.value==='reverse'){state={...state,direction:(-state.direction) as 1|-1};steps=state.players.length===2?2:1}if(card.value==='draw2'){state=drawTo(state,nextIndex(state,1),2);steps=2}if(card.value==='wild4'){state=drawTo(state,nextIndex(state,1),4);steps=2}return {...advance(state,steps),turnCount:s.turnCount+1}}
export function getBotAction(s:GameState){if(s.drawnThisTurn){if(s.lastDrawnCard){const wild=s.lastDrawnCard.value==='wild'||s.lastDrawnCard.value==='wild4';return {type:'play' as const,cardId:s.lastDrawnCard.id,chosenColor:wild?chooseColor(s):undefined}}return {type:'pass' as const}}const playable=getPlayableCards(s);if(!playable.length)return {type:'draw' as const};const rank:Record<string,number>={skip:5,reverse:5,draw2:5,wild4:4,wild:3};const card=[...playable].sort((a,b)=>(rank[b.value]??1)-(rank[a.value]??1))[0];const wild=card.value==='wild'||card.value==='wild4';return {type:'play' as const,cardId:card.id,chosenColor:wild?chooseColor(s):undefined}}
function chooseColor(s:GameState):Exclude<Color,'wild'>{const counts={red:0,blue:0,green:0,yellow:0} as Record<Exclude<Color,'wild'>,number>;for(const c of current(s).hand)if(c.color!=='wild')counts[c.color]++;return (Object.entries(counts).sort((a,b)=>b[1]-a[1])[0]?.[0]??'red') as Exclude<Color,'wild'>}
export const cardLabel:Record<Value,string>={skip:'SKIP',reverse:'↻',draw2:'+2',wild:'WILD',wild4:'+4', '0':'0','1':'1','2':'2','3':'3','4':'4','5':'5','6':'6','7':'7','8':'8','9':'9'};
